# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider "libvirt" do |v|
    v.memory = 1024
    v.cpus = 1
  end
  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    master.vm.network "private_network",
      :libvirt__network_name => "k3s-vagrant",
      :ip => "10.0.0.30",
      :libvirt__dhcp_enabled => false,
      :libvirt__forward_mode => "veryisolated"
  end
  config.vm.define "worker1" do |worker1|
    worker1.vm.hostname = "worker1"
    worker1.vm.network "private_network",
      :libvirt__network_name => "k3s-vagrant",
      :ip => "10.0.0.31",
      :libvirt__dhcp_enabled => false,
      :libvirt__forward_mode => "veryisolated"
  end
  config.vm.define "worker2" do |worker2|
    worker2.vm.hostname = "worker2"
    worker2.vm.network "private_network",
      :libvirt__network_name => "k3s-vagrant",
      :ip => "10.0.0.32",
      :libvirt__dhcp_enabled => false,
      :libvirt__forward_mode => "veryisolated"
  end
end
